// <auto-generated />
using System;
using DONGHONUOC_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DONGHONUOC_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DONGHONUOC_API.Models.DocChiSo", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("DocSoID");

                    b.Property<int?>("BVMT")
                        .HasColumnType("int")
                        .HasColumnName("BVMT");

                    b.Property<int?>("ChiSoCu")
                        .HasColumnType("int")
                        .HasColumnName("CSCu");

                    b.Property<int?>("ChiSoMoi")
                        .HasColumnType("int")
                        .HasColumnName("CSMoi");

                    b.Property<string>("Co")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CoMoi");

                    b.Property<string>("CodeCu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CodeCu");

                    b.Property<string>("DM")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DM");

                    b.Property<int?>("DMHN")
                        .HasColumnType("int")
                        .HasColumnName("DMHN");

                    b.Property<DateTime?>("DenNgay")
                        .HasColumnType("datetime2")
                        .HasColumnName("DenNgay");

                    b.Property<string>("Duong")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Duong");

                    b.Property<string>("GB")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GB");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChuDS");

                    b.Property<string>("GhiChuKH")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChuKH");

                    b.Property<string>("Hieu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HieuMoi");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HinhAnh");

                    b.Property<string>("Ky")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ky");

                    b.Property<string>("MaCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CodeMoi");

                    b.Property<string>("MaDanhBo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DanhBa");

                    b.Property<string>("MaLoTrinh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Dot");

                    b.Property<int?>("Nam")
                        .HasColumnType("int")
                        .HasColumnName("Nam");

                    b.Property<DateTime?>("NgayDoc")
                        .HasColumnType("datetime2")
                        .HasColumnName("GIOGHI");

                    b.Property<string>("NguoiDoc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NVGHI");

                    b.Property<string>("SoDienThoaiKH")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SDT");

                    b.Property<string>("SoNhaCu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SoNhaCu");

                    b.Property<string>("SoNhaMoi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SoNhaMoi");

                    b.Property<string>("SoThan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SoThanMoi");

                    b.Property<int?>("TBTT")
                        .HasColumnType("int")
                        .HasColumnName("TBTT");

                    b.Property<int?>("Thue")
                        .HasColumnType("int")
                        .HasColumnName("Thue");

                    b.Property<int?>("ThueTDVTN")
                        .HasColumnType("int")
                        .HasColumnName("BVMT_Thue");

                    b.Property<long?>("TienNuoc")
                        .HasColumnType("bigint")
                        .HasColumnName("TienNuoc");

                    b.Property<int?>("TieuThu")
                        .HasColumnType("int")
                        .HasColumnName("TieuThuMoi");

                    b.Property<int?>("TieuThuCu")
                        .HasColumnType("int")
                        .HasColumnName("TieuThuCu");

                    b.Property<long?>("TongTien")
                        .HasColumnType("bigint")
                        .HasColumnName("TongTien");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int")
                        .HasColumnName("TrangThai_API");

                    b.Property<DateTime?>("TuNgay")
                        .HasColumnType("datetime2")
                        .HasColumnName("TuNgay");

                    b.Property<string>("ViTri")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ViTriMoi");

                    b.HasKey("ID");

                    b.ToTable("DocSo");
                });

            modelBuilder.Entity("DONGHONUOC_API.Models.KyDoc", b =>
                {
                    b.Property<int>("MaKyDoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKyDoc"));

                    b.Property<DateTime?>("DenNgay")
                        .HasColumnType("datetime2")
                        .HasColumnName("DenNgay");

                    b.Property<int>("Ky")
                        .HasColumnType("int")
                        .HasColumnName("Ky");

                    b.Property<int>("Nam")
                        .HasColumnType("int")
                        .HasColumnName("Nam");

                    b.Property<DateTime?>("TuNgay")
                        .HasColumnType("datetime2")
                        .HasColumnName("TuNgay");

                    b.HasKey("MaKyDoc");

                    b.ToTable("Lich_DocSo");
                });

            modelBuilder.Entity("DONGHONUOC_API.Models.LichSuDocSo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ChiSo")
                        .HasColumnType("int")
                        .HasColumnName("ChiSo");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HanhDong");

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaCode");

                    b.Property<string>("MaDanhBo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaDanhBo");

                    b.Property<int>("MaKyDoc")
                        .HasColumnType("int")
                        .HasColumnName("MaKyDoc");

                    b.Property<string>("NguoiThucHien")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NguoiThucHien");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2")
                        .HasColumnName("ThoiGian");

                    b.Property<int>("TieuThu")
                        .HasColumnType("int")
                        .HasColumnName("TieuThu");

                    b.HasKey("ID");

                    b.ToTable("LichSuDocSo");
                });

            modelBuilder.Entity("DONGHONUOC_API.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaND");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<bool?>("Khoa")
                        .HasColumnType("bit")
                        .HasColumnName("Khoa");

                    b.Property<string>("VaiTro")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ChucVu");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("NguoiDungB");
                });
#pragma warning restore 612, 618
        }
    }
}
